version: "3"


networks:
  my-network:

services:

  # PUBLIC

  datasource:
    build: ./datasource
    ports:
      - "9010:9010"
    restart: always
    networks:
      - my-network
    volumes:
      - ./datasource/source:/source/

  # createaction:
  #   build: ./create-action
  #   ports:
  #     - "8090:8090"
  #   restart: always
  #   depends_on:
  #     - gotenberg
  #     - urlgenerator
  #   networks:
  #     - my-network

  nginx:
    image: nginx
    volumes:
      - ./staticfiles:/usr/share/nginx/html:ro
    ports:
      - "9020:80"
    networks:
      - my-network
  # INTERNAL SERVICES

  # available on 8080
  # pagegenerator:
  #   build: ./page-generator
  #   restart: always
  #   depends_on:
  #     - gotenberg
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./page-generator/templates:/templates/
  #   networks:
  #     - my-network

  # available on :3000
  gotenberg:
    image: gotenberg/gotenberg:7
    ports:
      - "3000:3000"
    networks:
      - my-network
